# Stage 1: Build the application

FROM node:24.0.2-alpine

WORKDIR /usr/src/app

# Copy package.json
COPY ["package.json", "pnpm-lock.yaml", ".env", "./"]

# Install & run pnpm
RUN npm install -g pnpm
RUN pnpm install

# Copy the rest of your application code
COPY . .

# Copy scripts:
COPY scripts ./scripts

# Add bash
RUN apk add --no-cache bash

# Build the application
RUN pnpm build
