# Stage 1: Build the application

FROM node:22-alpine

WORKDIR /usr/src/app

# Copy package.json and yarn.lock files
COPY ["package.json", "yarn.lock", ".yarnrc.yml", ".env", "./"]

# Enable yarn
RUN corepack enable
RUN yarn set version stable
RUN yarn install
RUN yarn

# Copy the rest of your application code
COPY . .

# Copy scripts:
COPY scripts ./scripts

# Add bash
RUN apk add --no-cache bash

# Build the application
RUN yarn build


