export interface IUser {
  id?: number; // id might be undefined when creating a new user, if it's auto-generated by the database
  email: string;
  password: string;
  username: string;
}

export class User implements IUser {
  constructor(
    public email: string,
    public password: string,
    public username: string,
    public id: number | undefined = undefined
  ) {}
}
