export interface IUser {
  id?: number; // id might be undefined when creating a new user, if it's auto-generated by the database
  email: string;
  password: string;
  username: string;
}

export class User implements IUser {
  id?: number;
  email: string;
  password: string;
  username: string;

  constructor({ email, password, username }: IUser) {
    this.email = email;
    this.password = password;
    this.username = username;
  }

  // Example method
  greet() {
    return `Hello, my username is ${this.username}`;
  }
}
