name: Deploy to Development

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to Development Server
        run: |
          cd ~/workspace/env
          git pull
          cat <<EOF | ./app1/update.sh dev
          no
          yes
          EOF
